# Generated by Django 4.2.2 on 2023-06-15 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='last_name')),
                ('email', models.CharField(db_index=True, max_length=100, verbose_name='email')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='city')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='online_cv/media/ptu12_cv/cv_pictures', verbose_name='picture')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_name', models.CharField(db_index=True, max_length=100, verbose_name='workplace_name')),
                ('date_from', models.DateField(default=django.utils.timezone.now, verbose_name='date_from')),
                ('date_until', models.DateField(default=django.utils.timezone.now, verbose_name='date_until')),
                ('duties', models.CharField(db_index=True, max_length=100, verbose_name='duties')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptu12_cv.cv', verbose_name='cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'work experience',
                'verbose_name_plural': 'work experiences',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_user', models.TextField(max_length=500, verbose_name='about_user')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptu12_cv.cv', verbose_name='cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'summary',
                'verbose_name_plural': 'summaries',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(db_index=True, max_length=100, verbose_name='skill')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptu12_cv.cv', verbose_name='cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(db_index=True, max_length=100, verbose_name='program')),
                ('date_from', models.DateField(default=django.utils.timezone.now, verbose_name='date_from')),
                ('date_until', models.DateField(default=django.utils.timezone.now, verbose_name='date_until')),
                ('school', models.CharField(choices=[('middle', 'Middle School'), ('high', 'High School'), ('home', 'Home Schooling'), ('vocational', 'Vocational School'), ('university/college', 'University/College'), ('certificate', 'Certificate')], db_index=True, default='middle', max_length=100, verbose_name='school')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptu12_cv.cv', verbose_name='cv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'educations',
            },
        ),
    ]
