# Generated by Django 4.2.2 on 2023-06-18 19:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ptu12_cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='extention',
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
