# Generated by Django 4.2.2 on 2023-06-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptu12_cv', '0003_education_degree_alter_cv_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='duties',
            field=models.TextField(db_index=True, max_length=100, verbose_name='duties'),
        ),
    ]
