# Generated by Django 4.2.2 on 2023-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptu12_cv', '0004_alter_workexperience_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='about_user',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='about_user'),
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
