# Generated by Django 4.2.2 on 2023-06-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrrepresentative',
            options={'verbose_name': 'hr representative', 'verbose_name_plural': 'hr representatives'},
        ),
    ]
