# Generated by Django 4.2.2 on 2023-06-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation', '0002_alter_hrrepresentative_options'),
        ('meeting_reservation', '0002_alter_hrrepresentative_options_and_more'),
    ]

    operations = [
    ]
