# Generated by Django 4.2.2 on 2023-06-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation', '0003_merge_20230620_0752'),
        ('meeting_reservation', '0003_merge_20230620_1029'),
    ]

    operations = [
    ]
