# Generated by Django 4.2.2 on 2023-06-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation', '0004_merge_20230620_1216'),
        ('meeting_reservation', '0004_merge_20230620_1303'),
    ]

    operations = [
    ]
