# Generated by Django 4.2.2 on 2023-06-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation', '0003_merge_20230621_1002'),
        ('meeting_reservation', '0005_merge_20230621_0619'),
    ]

    operations = [
    ]
